# Gunakan image node yang sesuai
FROM node:22-alpine

# Set working directory
WORKDIR /usr/src/app

# Salin file package.json dan package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Salin seluruh aplikasi ke dalam container
COPY . .

# Expose port untuk aplikasi
EXPOSE 3000

# Jalankan aplikasi (perintah default akan ditimpa oleh Docker Compose)
CMD ["npm", "run", "start:dev"]